### ISSUE TITLE
No currency showing

### ISSUE THREAD

**Issue by KaitoCross** [matteodanelli/MMM-cryptocurrency#30]
Hey :)
I've tried to configure the module, like described in the example, but no currency shows up, while the header does.

**Comment by matteodanelli** [comment]
Hello,

Can you post your configuration here? Where you have deployed the module (raspberry? which version?)

**Comment by kprasann1979** [comment]
Hi,

I've used as below only the header is showing, please help. Thank you!

                {
                        module: "MMM-cryptocurrency",
                        position: "top_left",
                        config: {
                                currency: ['ethereum', 'bitcoin'],
                                conversion: 'AUD',
                                showUSD: false,
                                headers: ['change24h', 'change7d'],
                                displayType: 'details',
                                showGraphs: true
                        }
                }

**Comment by matteodanelli** [comment]
Do you have another module in the same position? 
Have you fetch latest version?
I've tested with your configuration and it works :)

**Comment by kprasann1979** [comment]
Thanks for the response, I've noticed a typo "details" instead of "detail" in the displayType, it still doesn't work...I've pasted my config.js exactly as it is since i want to first test this configuration alone to start with...thanks for your time! Am I missing something on correct permissions...? After I restart mm, all I see is default header "CRYPTO CURRENCY" on top right...

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "0.0.0.0",
	port: 8080,
	ipWhitelist: [
        ],
	language: "en",
	units: "metric",
	modules: [
		{
			module: "MMM-cryptocurrency",
			position: "top_right",
			config: {
				currency: ['ethereum', 'bitcoin'],
				conversion: 'EUR',
				showUSD: false,
				headers: ['change24h', 'change1h', 'change7d'],
				displayType: 'logoWithChanges',
				showGraphs: true
			}
		}
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by matteodanelli** [comment]
Hi, I've tested same configuration and I have no problem. 
Are you able to see browser errors from developer tools? EG: On Chrome are under **More tools** --> **Developer tools** --> _Tab_ **console**.

Let me know and we'll solve soon :)

**Comment by kprasann1979** [comment]
Hi, thanks, managed to get it working finally! but being a noob, didn't understand how...checked there were two processes running  "mm" and "MagicMirror" whenever I did a "pm2 restart mm" which never reflected on getting the currency displayed (only the header displayed and changed as per displayType). I then tried a "pm2 restart MagicMirror" and now it works...
