### ISSUE TITLE
Crypto outside of the top 100 limit and issue with API calls.

### ISSUE THREAD

**Issue by GuyWithAQuestn** [matteodanelli/MMM-cryptocurrency#88]
One of the coins I'd like to track is fairly new, Chia (XCH), but it's currently ranked a little less than 3,000 (nowhere near the top 100).

If I change the Limit=100 to 3,000, my API Key Usage shoots up past the daily limit of 333 in a matter of seconds.

Is this just how it will work since this coin is ranked so lowly right now that I'd instead have to change the pulls to every other hour instead if I want to include XCH in my chart?

Thanks!!

PS - love this module.

**Comment by matteodanelli** [comment]
Well, this is caused by a coinmarketcap policy.
XCH is ranked around 2500, so it's correct to place the limit to 3000.
However , the api works as follow:
```
List-based endpoints track an additional call credit for every 100 data points returned (rounded up) beyond our 100 data point defaults.
```
That's the reason of the problem.
As you pointed out, the only fix is to reduce the frequency, with the **apiDelay** param.

I'm looking for a free provider, but nothing is completed as CoinMarketCap unfortunately.

**Comment by GuyWithAQuestn** [comment]
Thank you. 
Since I was getting 13 API pulls with each check, I changed apiDelay: 3600000 (in milliseconds, that makes it pull once an hour), which allows me to stay just slightly under the 333 limit that CoinMarketCap allows for free accounts.

Thank you!!!!
